# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-10 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': '广告内容类别', 'verbose_name_plural': '广告内容类别'},
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.CharField(max_length=300, verbose_name='内容链接'),
        ),
    ]
